# https://docs.helix-editor.com/configuration.html

theme = "autumn_night"

[editor]
line-number = "relative"
mouse = false
rulers = [100]
shell = ["bash", "-c"]
auto-save = true


[editor.soft-wrap]
enable = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.lsp]
auto-signature-help = true
display-inlay-hints = false
display-messages = true

[editor.whitespace.render]
tab = "all"

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-type"]
right = ["version-control", "diagnostics", "selections", "position", "file-encoding"]
separator = "|"

[keys.normal]
C-space = "signature_help"
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.insert]
C-space = "signature_help"
"C-[" = "normal_mode"
